import type { Config } from 'tailwindcss'
import TailwindUtopia from '@domchristie/tailwind-utopia'

export default <Partial<Config>>{
  theme: {
    extend: {
      fontFamily: {
        app: ['Helvetica', 'sans-serif'],
        landing: ['Inter', 'sans-serif'],
        logo: ['"Roboto Slab"', 'serif'],
        headline: ['Manrope', 'sans-serif'],
      },
      colors: {
        primary: 'var(--primary)',
        'tertiary-fixed': '#eaddff',
        'surface-container': '#eceef0',
        'primary-fixed-dim': '#ccbeff',
        outline: '#797488',
        'on-tertiary-fixed': '#25005a',
        'surface-container-high': '#e6e8ea',
        'surface-bright': '#f7f9fb',
        'on-secondary-container': '#fefcff',
        'secondary-container': '#316bf3',
        'on-tertiary-fixed-variant': '#5a00c6',
        surface: '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary': '#ffffff',
        'outline-variant': '#cac3d9',
        'primary-fixed': '#e7deff',
        'on-primary-container': '#e7deff',
        'on-surface': '#191c1e',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e0e3e5',
        'on-secondary-fixed': '#00174b',
        'on-tertiary-container': '#eaddff',
        'surface-tint': '#642ef4',
        'tertiary-fixed-dim': '#d2bbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#4c00d3',
        'primary-container': '#6b38fb',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-dim': '#d8dadc',
        'inverse-surface': '#2d3133',
        tertiary: '#6106d2',
        'on-secondary-fixed-variant': '#003ea8',
        'on-surface-variant': '#484456',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#dbe1ff',
        background: '#f7f9fb',
        'inverse-primary': '#ccbeff',
        'on-primary-fixed': '#1e0060',
        'surface-container-low': '#f2f4f6',
        'surface-variant': '#e0e3e5',
        'on-secondary': '#ffffff',
        'on-background': '#191c1e',
        secondary: '#0051d5',
        'tertiary-container': '#7a37eb',
      },
    },
  },
  content: [
    'components/**/*.vue',
    'layouts/**/*.vue',
    'pages/**/*.vue',
    'plugins/**/*.js',
    'nuxt.config.js',
  ],
  plugins: [
    TailwindUtopia,
  ],
}
